### ISSUE TITLE
GitHub Icon for GitHub buttons?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/openms.de#24]

**Comment by jpfeuffer** [comment]
The view on GitHub buttons  on applications could use a little icon. For me it is very intuitive to find GitHub icons to see the source.

**Comment by rahul799** [comment]
@jpfeuffer can you please review once?

**Comment by jpfeuffer** [comment]
Hmm does the button need to be full width? Can it be a bit rounded? And I think the icon could be a little bigger, with a margin that is at least as big as a whitespace.

**Comment by rahul799** [comment]
<img width="897" alt="Screenshot 2022-07-13 at 10 12 23 PM" src="https://user-images.githubusercontent.com/41531498/178786761-59386ff9-c10c-490b-a22d-76d48b8a7c17.png">

**Comment by rahul799** [comment]
> And I think the icon could be a little bigger, with a margin that is at least as big as a whitespace.

Sorry, I didn't understood the above point.

**Comment by rahul799** [comment]
Closing this issue as it's already fixed
