### ISSUE TITLE
Training page

### ISSUE THREAD

**Issue by enetz** [OpenMS/openms.de#29]
- the page looks nice, but how should the actual content be added and organized? will the images be links to 3 separate pages?
- would be nice to add the events from the old homepage, to show that we have regular developer and user meetings: https://www.openms.de/training/events/
- the new tutorials page isn't finished yet, but we can at least link to the existing Tutorial PDFs and workflows: https://www.openms.de/tutorials/  (not a link to this page, but adding the download links from there)

**Comment by rahul799** [comment]
Can we close this issue now?
