### ISSUE TITLE
Remove ALL UNUSED code/templates/...

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/openms.de#34]
This is a blocker and has high priority. Without that, no one will be able to understand how the homepage works.

**Comment by rahul799** [comment]
Done.

**Comment by rahul799** [comment]
Can we close this?

**Comment by jpfeuffer** [comment]
Can you link the PR? I need to see what you removed to say if it is completed.

**Comment by rahul799** [comment]
https://github.com/OpenMS/openms.de/commit/e530337413da5b3eb58bac92239b7a0e7ade2520#diff-c6ad0f33f07a697ee17a6667276cba4d8bb779e5b0116fa204ab8e30a073a77d

**Comment by jpfeuffer** [comment]
It seems to me like the diversity statement is still a copy of scipy. I have never heard about any of those names.

**Comment by rahul799** [comment]
Marking this issue as completed. Thankyou for pointing out @jpfeuffer
