### ISSUE TITLE
Nicer icon for Tips and Hints

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/openms.de#36]
Currently, it looks like an icon is missing with that Unicode "?".

**Comment by rahul799** [comment]
<img width="894" alt="Screenshot 2022-07-15 at 8 25 51 PM" src="https://user-images.githubusercontent.com/41531498/179249534-46d6e2d7-7029-4a40-9fdc-7b0db96bd6a4.png">

<img width="856" alt="Screenshot 2022-07-15 at 8 26 13 PM" src="https://user-images.githubusercontent.com/41531498/179249545-ae0a30aa-c0bb-4f31-8a1a-21ae880e2d45.png">

<img width="883" alt="Screenshot 2022-07-15 at 8 26 30 PM" src="https://user-images.githubusercontent.com/41531498/179249564-547620f3-6408-4e5b-ba43-60a54e833637.png">

<img width="887" alt="Screenshot 2022-07-15 at 8 26 39 PM" src="https://user-images.githubusercontent.com/41531498/179249583-8b23610d-1396-4cd2-bd8d-31647627ef41.png">

**Comment by jpfeuffer** [comment]
yes nice!

**Comment by rahul799** [comment]
Changes Pushed. Thankyou for pointing it out 😃
