### ISSUE TITLE
Improvements for "Help request" web page

### ISSUE THREAD

**Issue by tjeerdijk** [OpenMS/openms.de#38]
See comments in screenshot

![Screenshot_OpenMS_Web-Site_Bug-Report-Form](https://user-images.githubusercontent.com/26492048/179789284-f1a31057-6d16-4239-abee-9f6f72a825a4.png)

**Comment by rahul799** [comment]
Hi @tjeerdijk 
Thankyou for pointing out the issues.
I have fixed all of them.

Q- Can users upload screenshots or error logs?
A- Sadly google won't allow upload button in iframes. So maybe the user can upload the document to google drive and can send us the link.

**Comment by tjeerdijk** [comment]
Thx @rahul799 . About uploading screenshots or error logs. Yes, google drive is certainly possible. As an alternative, would it also be possible to upload those in GitHub. In detail (1) a person fills out the OpenMS "Bug report, help or feature request" (2) this google form generates a GitHub issue and reports the issue number back to person via email (3) the Epson has the option of editing the GitHub issue and adding screenshots or error logs.

Would such a three-step approach be feasible?

**Comment by rahul799** [comment]
Hi @tjeerdijk, I will explore it more.

**Comment by rahul799** [comment]
And I have wrote everything in english, so It might be due to some misconfiguration from google translator that you are getting some sentences in german.

**Comment by tjeerdijk** [comment]
My educated guess is that google forms tries to be "helpful" and fills in anything that you left unspecified in the local language. I happen to also have an account in The Netherlands and when I VPN to that one, the text is indeed in Dutch not German. So. I'm guessing there is some metavalue that you need to set so everything stays in English. There is some discussion (but no complete answer) here: https://support.google.com/docs/thread/14228820/selecting-language-of-a-google-form-by-using-hl-xx-doesn-t-work-for-me?hl=en

**Comment by rahul799** [comment]
Closing the issue as discussed on call.
