### ISSUE TITLE
Long description text under "Help request" is too long

### ISSUE THREAD

**Issue by tjeerdijk** [OpenMS/openms.de#39]
Replace "For bug reporting, please include enough information for us to reproduce the bug or paste the few last lines of logs . For proposed new features, adding a use case that lets helps us understand how you intend to use new features or tools is incredibly helpful for us, both in development and in understanding how our user community accesses and uses data from OpenMS. Clarity helps, but we can always follow up if you supply your email (next questions)."

with
"For bug reporting, include enough information to reproduce the bug and paste the few last lines of logs. For proposed new features, add a use case that helps us understand how you intend to use new features or tools."

**Comment by rahul799** [comment]
Done

**Comment by tjeerdijk** [comment]
Thx
