### ISSUE TITLE
Issues with main page of new web site

### ISSUE THREAD

**Issue by tjeerdijk** [OpenMS/openms.de#40]
1. replace red with blue
2. keep quick facts as on old web site
3.  use pyOpenMS logo from last years cheatsheet (attached as pdf but original in pptx) 

[pyOpenMS_Cheatsheet.pdf](https://github.com/OpenMS/openms.de/files/9143058/pyOpenMS_Cheatsheet.pdf)

**Comment by jpfeuffer** [comment]
Can the shadows of the key features boxes be darker blue, to match the design?

I liked the red as an accent/contrast color but I agree that it is currently too much red.

**Comment by rahul799** [comment]
@jpfeuffer do you like the shadows now?

**Comment by jpfeuffer** [comment]
No, sorry, still purple

**Comment by rahul799** [comment]
No issues. This time I have used the exact [hash](https://www.color-hex.com/color/0c2a60) 😄 & opacity 40%  .

**Comment by jpfeuffer** [comment]
Yep looks good

**Comment by rahul799** [comment]
Done
