### ISSUE TITLE
Rename "Quick Facts" to "Quick Facts for Developers" and add "Quick Facts for Users"

### ISSUE THREAD

**Issue by tjeerdijk** [OpenMS/openms.de#41]
The current "quick facts" is very developer focussed. Add a user-focussed quick facts with
1. current release number (2.8)
2. supported operating systems (Windows 7,8,10 and 11), MacOS 10.13+ (check with Julianus) and Ubuntu 2018.04+
3. supported workflow engines (KNIME, Galaxy and NextFlow)
4. supported Python version with pyOpenMS 3.6, 3.7, 3.8 and 3.9 (check with Julianus)

**Comment by rahul799** [comment]
Done

**Comment by rahul799** [comment]
Closing it as it's already fixed. Thankyou.
