### ISSUE TITLE
"Community" page

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/openms.de#42]
Issues:

- [x] "_Please note ..."
- [x] OpenMS General mailing list is NOT for announcements. There is openms-announcements! 
- [x] Not sure if mailing list is a good place for longer-form discussions but also not the worst place.
- [x] "For bug reports;"
- [x] For bullet points, always have a sentence:
  ```
  The issue tracker is for:
  - bug reports (why is there no example??)
  - documentation issues (e.g. “I found this section unclear”), and
  - feature requests (e.g. “I would like to have a new interpolation method in spectrum.sortByPosition()”).
  ```
  Also, you would need to make a distinction on which issue tracker(s). I don't want doc issues in the OpenMS main repo 
  for example. Or at least mention that there are multiple repos and you should choose carefully.
- [x] "openms" Please check the WHOLE website

**Comment by tjeerdijk** [comment]
1. The heading "PARTICIPATE ONLINE" and sentence "The following are ways to engage directly with the OpenMS project and community. _Please note that we encourage users and community members to support each other" are superfluous and can go IMHO
2. Please always use "OpenMS" and not "openms"
3.  In the Discord description there are two typos "Similar to Gitter, Discord allows the users to comminucate in different channels, publically as well as privately." -> Similar to Gitter, Discord allows the users to communicate in different channels, publicly as well as privately.

**Comment by rahul799** [comment]
Can you please send me the link for **openms-announcements** mailing list?

**Comment by jpfeuffer** [comment]
https://sourceforge.net/p/open-ms/mailman/open-ms-announcements

**Comment by rahul799** [comment]
Thankyou @jpfeuffer.

**Comment by rahul799** [comment]
Can we close this issue now @jpfeuffer

**Comment by jpfeuffer** [comment]
No, there are no links to the mailing lists, and the distinction that there are actually TWO mailing lists is too unclear.

**Comment by rahul799** [comment]
@jpfeuffer can we close this issue now ?
