### ISSUE TITLE
Change items and order under "installation"

### ISSUE THREAD

**Issue by tjeerdijk** [OpenMS/openms.de#43]
Installations instructions text should read: 
1. If you are new to computational mass spectrometry, we suggest you read the "tutorial computational mass spectrometry" [this tutorial is to be developed from CZI money, now make a placeholder]
2. if you have a data set and want to analyse the data we suggest you use the workflow engine KNIME. Download instructions are here (point to https://staging-openms.readthedocs.io/en/staging/docs/run-workflows-with-openms-tools/openms-in-knime.html) and a tutorial is here (point to https://staging-openms.readthedocs.io/en/staging/docs/tutorials-and-quickstart-guides/tutorials.html#constructing-a-workflow-in-knime)
3. if you want to visually inspect mass spectra or chromatograms, we suggest you use TOPPView. Download instructions for TOPPView and the OpenMS library and tools are given below.
4. If you have used OpenMS before or want to have maximal control over your workflow, we suggest you use the OpenMs tools and library and write your own shell scripts. Download instructions are given below.
5. If you are familiar with Python and want to write your own analysis scripts, check out pyOpenMS (https://pyopenms.readthedocs.io/en/latest/#)
6. If you have a large data set and access to compute server, check our Galaxy (https://staging-openms.readthedocs.io/en/staging/docs/run-workflows-with-openms-tools/openms-in-nextflow.html) and NextFlow (https://staging-openms.readthedocs.io/en/staging/docs/run-workflows-with-openms-tools/openms-on-galaxy.html) tutorials

**Comment by timosachsenberg** [comment]
I like it. There are some mixups like the links for galaxy and nextflow are switched.

To break the list down a bit, we could think if we could organize this a bit according to thise (in my view distinct) user groups:

Users that:
- Apply tools and run existing workflows
- Modify and create own workflows
- Enhance their workflows with small pyOpenMS scripts or develop novel methods or small tools using pyOpenMS

Advanced users that:
- Develop high-performance tools or algorithms with the C++ OpenMS library
- Run workflows on very large datasets on powerful compute infrastructure

**Comment by jpfeuffer** [comment]
I agree. We wanted the homepage to be a first contact point that distributes people to the other documentations.
I think such an overview page should be very prominent.

**Comment by rahul799** [comment]
This issue is fixed.
