### ISSUE TITLE
Smartphone layout too wide

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/openms.de#48]
Probably due to the huge pyopenms logo.

**Comment by rahul799** [comment]
Fixed. Now the tags are bit misaligned. Will fix them too.

**Comment by rahul799** [comment]
This is fixed now.

**Comment by jpfeuffer** [comment]
Yes thanks. Only the quickfacts are not really centered.

**Comment by jpfeuffer** [comment]
Done.
