### ISSUE TITLE
Rethink the terminal section in the homepage

### ISSUE THREAD

**Issue by rahul799** [OpenMS/openms.de#50]

**Comment by rahul799** [comment]
@jpfeuffer any suggestions for the sample code that can be used?

**Comment by jpfeuffer** [comment]
code or command line?

**Comment by jpfeuffer** [comment]
https://asciinema.org/

and then `FileInfo -in ./share/OpenMS/examples/BSA1.mzML`

**Comment by jpfeuffer** [comment]
ah! you can customize what it prints? I see that it prints some "fake" OpenMS calls in the beginning, but after that complete nonsense.

**Comment by jpfeuffer** [comment]
If you want to continue using that, you should show one of the C++ tools as mentioned above. Just pick any, and copy the output from a real execution. You can pick any easy tool from the tutorials.

**Comment by rahul799** [comment]
Thanks @jpfeuffer. It's fixed now.

**Comment by jpfeuffer** [comment]
Nice. A little too big for  desktop mode on a phone but that is probably not so important
