### ISSUE TITLE
Restructure community page

### ISSUE THREAD

**Issue by rahul799** [OpenMS/openms.de#52]
https://openms.github.io/community/

**Comment by rahul799** [comment]
Ex: https://github.com/OpenMS/.github/tree/main/profile

**Comment by rahul799** [comment]
Use buttons in the heading instead of link.

**Comment by rahul799** [comment]
@jpfeuffer I have pushed my changes. Can you please review ?
Thankyou

**Comment by jpfeuffer** [comment]
![Bildschirmfoto 2022-08-09 um 15 43 42](https://user-images.githubusercontent.com/8102638/183664797-234a6e9c-c683-45e2-a165-66f0baf87a0e.png)

I think they meant those buttons. Maybe we can also have some icons on the buttons.

**Comment by jpfeuffer** [comment]
Or these shields:

https://img.shields.io/static/v1?style=for-the-badge&message=Gitter&color=ED1965&logo=Gitter&logoColor=FFFFFF&label=

https://img.shields.io/static/v1?style=for-the-badge&message=Discord&color=5865F2&logo=Discord&logoColor=FFFFFF&label=

**Comment by rahul799** [comment]
I have added the badges in the heading. I think the below one's are looking fine and don't need to be replaced.

**Comment by jpfeuffer** [comment]
Can you use the same style at least? This were just some suggestions.

**Comment by rahul799** [comment]
Done.

**Comment by jpfeuffer** [comment]
thanks
