### ISSUE TITLE
Add nextflow workflows and maybe use GitHub cards

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/openms.de#54]
old code 
```
<script async src="https://cdn.rawgit.com/tsucres/GithubManyfacedCards/0.3.0/dist/gmc-loader.min.js" data-gmc-repo="nf-core/mhcquant" data-gmc-theme="gh_recommendation"></script>
<div>[button link="https://nf-co.re/launch?pipeline=mhcquant" color="custom" size="" stretch="" type="flat" shape="" target="_self" title="" gradient_colors="#0340ae|#0340ae" gradient_hover_colors="|" accent_color="#ffffff" accent_hover_color="#ffffff" bevel_color="" border_width="" icon="fa-rocket" icon_position="left" icon_divider="yes" modal="" animation_type="" animation_direction="" animation_speed="1" alignment="center" class="" id=""]Launch[/button]</div>
</div>
</div>
```

**Comment by jpfeuffer** [comment]
NIce but:
- can you make the buttons smaller?
- can you style the Star buttons to be better visible?

**Comment by jpfeuffer** [comment]
and add some separator in between

**Comment by jpfeuffer** [comment]
and the link name contains a whitespace when hovered. can we reduce the height of the button as well?`

**Comment by jpfeuffer** [comment]
you should not use invisible spaces! why not use a margin property or something like that?

**Comment by jpfeuffer** [comment]
you definitely need to style the css more finegrained. A Github button is not the same as our button for example

**Comment by rahul799** [comment]
I am not sure if I can change the color of the github star button or anything which is part of the card as it is rendered using the js code. I think in that case I will have to make a new template as right now I am using [this](https://github.com/tsucres/GithubManyfacedCards/tree/master/dist/themes/gh_recommendation) one.

**Comment by jpfeuffer** [comment]
You already do! In a bad way:
https://github.com/OpenMS/scientific-python-hugo-theme/blob/d1346fd154dff9d59e3289a37de3f3b8f8a07d82/assets/theme-css/buttons.css#L4

You should give our own buttons an own class and avoid forcing styles with !important

**Comment by rahul799** [comment]
This is for the Launch button. I am talking about the star button.
<img width="965" alt="Screenshot 2022-08-10 at 8 44 20 PM" src="https://user-images.githubusercontent.com/41531498/183941179-c4ea8d16-e340-4f19-b13e-c6807c14f598.png">

**Comment by jpfeuffer** [comment]
Me too. the star button is of class ".btn"

**Comment by jpfeuffer** [comment]
and you are forcing its font color to white!

**Comment by rahul799** [comment]
oh God 😄 ... Actually they have also used the same class. Got it.

**Comment by jpfeuffer** [comment]
Yeah but I don't blame them. It is a standard name. You should have a second class in your CSS I think, to only affect the buttons that you want.

**Comment by jpfeuffer** [comment]
Or: dont use important

**Comment by rahul799** [comment]
Yeah true. I have pushed my changes. I think I will have to do some cleaning in css. Anyways thankyou @jpfeuffer.

**Comment by jpfeuffer** [comment]
Looks good now. Yes, maybe cleanup but this issue is done
