### ISSUE TITLE
Remove the known issue from install page

### ISSUE THREAD

**Issue by rahul799** [OpenMS/openms.de#55]

**Comment by jpfeuffer** [comment]
You mean the macOS one? 
Actually, I am not so sure. Unfortunately, this is almost a requirement these days and it is hard to recognize since just nothing will happen when you click the app. I would vote for leaving it.

**Comment by rahul799** [comment]
ok. So I think installation page is fine for now? @tjeerd

**Comment by tjeerdijk** [comment]
No the installation page is not (yet) fine, see my suggestions here: https://docs.google.com/document/d/1hvSd3O1OXWdEW8jCeRrHikcbtcqxOuodfZsDIa8Yosg/edit

On 9. Aug 2022, at 11:22, Rahul Agrawal ***@***.******@***.***>> wrote:



ok. So I think installation page is fine for now?

cc: @tjeerdijk<https://github.com/tjeerdijk>
