### ISSUE TITLE
Separation of groups on the homepage could be improved

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/openms.de#59]
1. I do not like the styling of the headers, e.g. `OpenMS allows users`. The font is different than the rest, and smaller than the following headings.
2. I think the group headers could also use a *little* bit more visual distinction than just the separator line, which is barely visible for some of the colors.
3. The grouping is currently hacked, in the sense that the group headers are faked into the first item of each group. Would be better if that was represented in the template.

**Comment by jpfeuffer** [comment]
please adapt the theme to look like the following:

- heroGroup
  title: Users
  bgcolor: xyz
  heroItems:
  - hero: workflows
  - hero: tools  

- heroGroup
   title: Devs
   bgcolor: xyz
   heroItems:
    - hero: c++
    - hero: pyopenms


Do NOT use keyfeatures classes in the hero partials!

**Comment by jpfeuffer** [comment]
While you are at it, remove all the dead code in the config.yaml. There are a lot of items completely unused which confused me a lot.

**Comment by rahul799** [comment]
Yes, I am on it and will raise a PR today.

**Comment by rahul799** [comment]
Hey @jpfeuffer,
If I follow below theme

> * heroGroup
>   title: Users
>   bgcolor: xyz
>   heroItems:
>           - hero: workflows
>           - hero: tools


I will need to create a common template for the heroitems, but right now the image placement is not same e.g. https://github.com/OpenMS/openms.de/blob/main/layouts/partials/apply-workflows.html#L14 & https://github.com/OpenMS/openms.de/blob/main/layouts/partials/create-workflows.html#L26
So it will be bit tricky.

**Comment by jpfeuffer** [comment]
Why is this? Why can it not be the same style? Would be much easier to maintain. Or give the template another attribute if it is just two styles.

**Comment by rahul799** [comment]
Actually I am talking about the placement of images, like [here](https://github.com/OpenMS/openms.de/blob/main/layouts/partials/apply-workflows.html#L14 ) the [title](https://github.com/OpenMS/openms.de/blob/main/layouts/partials/apply-workflows.html#L20) is below the image whereas it's opposite in [this](https://github.com/OpenMS/openms.de/blob/main/layouts/partials/create-workflows.html#L13) case.

**Comment by jpfeuffer** [comment]
You mean such that they are placed left  or right of the text?
Yes, then make an attribute imgLocation: left/right

Or if possible, count the number of items. If divisible by two, place it left, otherwise right.

**Comment by jpfeuffer** [comment]
https://discourse.gohugo.io/t/how-counting-up-a-variable-in-range/586/5

Similar to this.

**Comment by rahul799** [comment]
Ok. Got it.

**Comment by jpfeuffer** [comment]
Much better, but:
- there is a "-" after the group heading somehow for me.
- the bottom of the colored background is not rounded, looks a bit weird
- can we make the group heading h1 and the item headings an h2. With the same font type?

**Comment by rahul799** [comment]
Fixed

**Comment by jpfeuffer** [comment]
Perfect thanks
