### ISSUE TITLE
From form: The webpage for the MetaProSIP will not open and I cannot figure out how to operate the software with openMS

### ISSUE THREAD

**Issue by rahul799** [OpenMS/openms.de#67]
When I try to open the link I am directed to a webpage that says "This site can’t provide a secure connection" and it appears that the site does not exist -- I want to use the pipeline that is supposedly delineated on the website 

*This issue was autogenerated by the Google Form for [Features](https://forms.gle/QVcA3NktyGmxm2CZ7)*

Name: Abigail Cragin

Email: abc7008@med.cornell.edu

**Comment by jpfeuffer** [comment]
Hi!

Which link do you mean?

The page for the application is here:
https://www.openms.de/application/metaprosip/

**Comment by timosachsenberg** [comment]
I answered the person. The linked pipeline was missing.
